version: 2
updates:
  - package-ecosystem: docker
    directory: "/docker"
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 3
    labels:
      - dependencies
      - docker
    commit-message:
      prefix: "chore(docker)"
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
      day: monday
    labels:
      - dependencies
      - github-actions
    commit-message:
      prefix: "chore(actions)"
